### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by ekmartin** [tomkis1/js-autoimport#1]
Would be nice to have an option to enable semicolons for imports, i.e.
`import express from 'express';`

**Comment by tomkis** [comment]
Thanks for the suggestion. I will implement this together with space between braces for named imports.

**Comment by tomkis** [comment]
Implemented in `9ebc174`, you may install this via `apm` in version `0.5.0`

**Comment by ekmartin** [comment]
Cool, thanks!
