### ISSUE TITLE
This package is the worst- fork bomb-like activity

### ISSUE THREAD

**Issue by doubleUTF** [tomkis1/js-autoimport#16]
Right after I installed this package, my Atom started to continuously opening a bunch of files along with multiple instances of Atom which looked like a fork bomb. I closed the program and reopened it trying to uninstall but the same thing happened. Finally, I had to go to the command prompt and hit 'apm uninstall js-autoimport' to get rid of this garbage. Fix this crap or take it down.

**Comment by tomkis** [comment]
Unpublished, this project is no-longer maintained and does not even make sense in current JavaScript environment.
