### ISSUE TITLE
Prints ${spaceForNamedImports} in import statement

### ISSUE THREAD

**Issue by ghengeveld** [tomkis1/js-autoimport#2]
When autoimporting, this is what I get:

```
import Hapi${spaceForNamedImports} from 'hapi';
```

I tried to investigate the source of the problem, but the code that seems to be related (ImportOrganiser.js around line 60) is way too complex imho.

Disabling the spaceForNamedImports setting does not make a difference.

**Comment by osiloke** [comment]
+1

**Comment by SebastianTroc** [comment]
+1
